services:
  - type: web
    name: gerador-devocional-render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: OPENAI_API_KEY
        sync: false